# Generated by Django 2.1 on 2018-09-15 19:50

from django.db import migrations, models
import django.db.models.deletion
import opinionated_reporting.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opinionated_reporting', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_is_dirty', models.BooleanField(default=False)),
                ('_is_frozen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_is_dirty', models.BooleanField(default=False)),
                ('_is_frozen', models.BooleanField(default=False)),
                ('created_on', opinionated_reporting.fields.DimensionForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_created_on', to='opinionated_reporting.DateDimension')),
                ('customer', opinionated_reporting.fields.DimensionForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.CustomerDimension')),
                ('hour_ordered_on', opinionated_reporting.fields.DimensionForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_hour_ordered_on', to='opinionated_reporting.HourDimension')),
                ('hour_reated_on', opinionated_reporting.fields.DimensionForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_hour_created_on', to='opinionated_reporting.HourDimension')),
                ('ordered_on', opinionated_reporting.fields.DimensionForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_ordered_on', to='opinionated_reporting.DateDimension')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProductFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_is_dirty', models.BooleanField(default=False)),
                ('_is_frozen', models.BooleanField(default=False)),
                ('order_id', opinionated_reporting.fields.IntegerDescriptionField()),
                ('created_on', opinionated_reporting.fields.DimensionForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedproduct_created_on', to='opinionated_reporting.DateDimension')),
                ('customer', opinionated_reporting.fields.DimensionForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.CustomerDimension')),
                ('hour_created_on', opinionated_reporting.fields.DimensionForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedproduct_hour_created_on', to='opinionated_reporting.HourDimension')),
                ('hour_ordered_on', opinionated_reporting.fields.DimensionForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedproduct_hour_ordered_on', to='opinionated_reporting.HourDimension')),
                ('ordered_on', opinionated_reporting.fields.DimensionForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedproduct_ordered_on', to='opinionated_reporting.DateDimension')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_is_dirty', models.BooleanField(default=False)),
                ('_is_frozen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ordered_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.TestCustomer')),
            ],
        ),
        migrations.CreateModel(
            name='TestOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.TestOrder')),
            ],
        ),
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='testorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.TestProduct'),
        ),
        migrations.AddField(
            model_name='testorder',
            name='products',
            field=models.ManyToManyField(through='tests.TestOrderItem', to='tests.TestProduct'),
        ),
        migrations.AddField(
            model_name='orderedproductfact',
            name='product',
            field=opinionated_reporting.fields.DimensionForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.ProductDimension'),
        ),
    ]
