# Generated by Django 2.1 on 2018-09-17 00:56

from django.db import migrations, models
import django.db.models.deletion
import opinionated_reporting.fields


class Migration(migrations.Migration):

    replaces = [('tests', '0001_initial'), ('tests', '0002_auto_20180915_1952'), ('tests', '0003_auto_20180916_1525'), ('tests', '0004_auto_20180916_1523'), ('tests', '0005_auto_20180916_1530'), ('tests', '0006_orderedfact_total'), ('tests', '0007_auto_20180916_2053')]

    initial = True

    dependencies = [
        ('opinionated_reporting', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_is_dirty', models.BooleanField(default=False)),
                ('_is_frozen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_is_dirty', models.BooleanField(default=False)),
                ('_is_frozen', models.BooleanField(default=False)),
                ('created_on', opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_created_on', to='opinionated_reporting.DateDimension')),
                ('customer', opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.CustomerDimension')),
                ('hour_ordered_on', opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_hour_ordered_on', to='opinionated_reporting.HourDimension')),
                ('hour_created_on', opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_hour_created_on', to='opinionated_reporting.HourDimension')),
                ('ordered_on', opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_ordered_on', to='opinionated_reporting.DateDimension')),
                ('_unique_identifier', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProductFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_is_dirty', models.BooleanField(default=False)),
                ('_is_frozen', models.BooleanField(default=False)),
                ('order_id', opinionated_reporting.fields.IntegerDescriptionField()),
                ('created_on', opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderedproduct_created_on', to='opinionated_reporting.DateDimension')),
                ('customer', opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.CustomerDimension')),
                ('hour_created_on', opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderedproduct_hour_created_on', to='opinionated_reporting.HourDimension')),
                ('hour_ordered_on', opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderedproduct_hour_ordered_on', to='opinionated_reporting.HourDimension')),
                ('ordered_on', opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderedproduct_ordered_on', to='opinionated_reporting.DateDimension')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_is_dirty', models.BooleanField(default=False)),
                ('_is_frozen', models.BooleanField(default=False)),
                ('_unique_identifier', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='', max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ordered_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.TestCustomer')),
            ],
        ),
        migrations.CreateModel(
            name='TestOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.TestOrder')),
            ],
        ),
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='testorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.TestProduct'),
        ),
        migrations.AddField(
            model_name='testorder',
            name='products',
            field=models.ManyToManyField(through='tests.TestOrderItem', to='tests.TestProduct'),
        ),
        migrations.AddField(
            model_name='orderedproductfact',
            name='product',
            field=opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.ProductDimension'),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='testorderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerdimension',
            name='_unique_identifier',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdimension',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedproductfact',
            name='_unique_identifier',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdimension',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedproductfact',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderedproductfact',
            name='created_on',
            field=opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderedproduct_created_on', to='opinionated_reporting.DateDimension'),
        ),
        migrations.AlterField(
            model_name='orderedproductfact',
            name='customer',
            field=opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.CustomerDimension'),
        ),
        migrations.AlterField(
            model_name='orderedproductfact',
            name='hour_created_on',
            field=opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderedproduct_hour_created_on', to='opinionated_reporting.HourDimension'),
        ),
        migrations.AlterField(
            model_name='orderedproductfact',
            name='hour_ordered_on',
            field=opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderedproduct_hour_ordered_on', to='opinionated_reporting.HourDimension'),
        ),
        migrations.AlterField(
            model_name='orderedproductfact',
            name='ordered_on',
            field=opinionated_reporting.fields.DimensionForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderedproduct_ordered_on', to='opinionated_reporting.DateDimension'),
        ),
    ]
