# Generated by Django 2.1 on 2018-09-17 00:58

from django.db import migrations, models
import opinionated_reporting.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_squashed_0007_auto_20180916_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfact',
            name='_unique_identifier',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderedproductfact',
            name='order_id',
            field=opinionated_reporting.fields.IntegerDescriptionField(default=0),
        ),
        migrations.AlterField(
            model_name='orderedproductfact',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productdimension',
            name='_unique_identifier',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productdimension',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
