# Generated by Django 2.1 on 2018-09-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20180916_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproductfact',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
