# Generated by Django 2.1 on 2018-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20180916_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdimension',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedproductfact',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
