# Generated by Django 2.1 on 2018-09-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20180916_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedfact',
            old_name='hour_reated_on',
            new_name='hour_created_on',
        ),
    ]
